"""Create UserFlashcardSet and UserNotebook tables

Revision ID: 5050d9a08c15
Revises: 84ff1262d999
Create Date: 2024-06-26 19:02:54.641262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5050d9a08c15'
down_revision = '84ff1262d999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_flashcard_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_set_id'], ['flashcard_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notebook')
    op.drop_table('user_flashcard_set')
    # ### end Alembic commands ###
