"""create flashcardset and flashcard table

Revision ID: 82f7e045f3e4
Revises: 603c19f7f3e4
Create Date: 2024-06-25 00:35:42.713783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f7e045f3e4'
down_revision = '603c19f7f3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_set_name'), ['name'], unique=False)

    op.create_table('flashcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flashcard_set_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_set_id'], ['flashcard_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard')
    with op.batch_alter_table('flashcard_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_set_name'))

    op.drop_table('flashcard_set')
    # ### end Alembic commands ###
